title: 学习笔记
SEOTitle: ZFX
author: 小张
timezone: Asia/Shanghai
paginate: 10
paginate_path: "page:num"
highlighter: rouge
url: "https://www.zfxkj.top"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM

gems: [jekyll-paginate, jekyll-sitemap, jekyll-feed]

disqus: zfx521
disqus_base: http://www.zfxkj.top/

# https://developers.google.com/analytics/devguides/collection/analyticsjs/
google_analytics_id: UA-97824262-2
google_analytics_domain: auto

permalink: /blog/:year/:month/:day/:title/

header-img: /img/default-bg.jpg
WeChatPublic: https://pan-1256416840.cos.ap-beijing.myqcloud.com/qrcode_WeChatPublic.jpg
zfb_pay: https://pan-1256416840.cos.ap-beijing.myqcloud.com/zfb_pay.jpg
wx_pay: https://pan-1256416840.cos.ap-beijing.myqcloud.com/wx_pay.jpg

RSS: feed.xml
categories_path: categories
tags_path: tags
archive_path: archives
about_path: about

BASE_PATH:

qq: 2675699284
gitee_username: ZFX521
zhihu_username: ZFXKJ
weibo_username:     
facebook_username:
github_username: ZFXkj
email: 2675699284@qq.com
linkedin:

#  default.html footer
anchorjs: true

# page Sidebar settings
sidebar-about-description: "ZFX 学习笔记"
sidebar-avatar: https://avatars.githubusercontent.com/u/31238863

#备案号
bah: "豫ICP备2021032942号"

# 友链
friends: [
  {
    title: "GitHub下载加速",
    href: "https://ghapi.zfb132.workers.dev/"
  },
  {
    title: "ZFX工具",
    href: "https://zfx521.gitee.io/"
  },
  {
    title: "常用API",
    href: "http://lkaa.top/"
  }
]
