title: 学习笔记
SEOTitle: ZFX
author: 小张
timezone: Asia/Shanghai
paginate: 10
paginate_path: "page:num"
highlighter: rouge
url: "https://www.zfx521.top"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM

gems: [jekyll-paginate, jekyll-sitemap, jekyll-feed]

disqus: zfx521
disqus_base: http://www.zfx251.top/

# https://developers.google.com/analytics/devguides/collection/analyticsjs/
google_analytics_id: UA-97824262-2
google_analytics_domain: auto

permalink: /blog/:year/:month/:day/:title/

header-img: /img/default-bg.jpg
WeChatPublic: /img/qrcode_WeChatPublic.jpg
zfb_pay: /img/zfb_pay.jpg
wx_pay: /img/wx_pay.jpg

RSS: feed.xml
categories_path: categories
tags_path: tags
archive_path: archives
about_path: about

BASE_PATH:

zhihu_username: 
weibo_username:     
facebook_username:
github_username:    ZFX521
google_username:    
email: 2675699284@qq.com
linkedin:

#  default.html footer
anchorjs: true

# page Sidebar settings
sidebar-about-description: "ZFX 学习笔记"
sidebar-avatar: /img/me2.jpg

# Friends
friends: [
  {
    title: "GitHub下载加速",
    href: "https://ghapi.zfb132.workers.dev/"
  }
]
